# Setup
title:               Data Science Project Blog
tagline:             'IFT6758 - Data Science'
description:         'Blog for the IFT6758 Data Science course project.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alicia Vaquero, Ariane Champagne, Kessigen Ramasubboo
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Repo files that should not be published with the site
exclude:
  - README.md
  - LICENSE.md
  - plotly_html.ipynb

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
